# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='emplyee_id',
            new_name='employee_id',
        ),
    ]
