# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180701_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='status',
            field=models.CharField(default='pending', max_length=250),
        ),
    ]
